import "@/styles/globals.css";
import "@/styles/fonts.css";

import type { Metadata } from "next";

import Layout from "@/components/Layout";

export const metadata: Metadata = {
  title: "베이스",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Layout title="base">{children}</Layout>
      </body>
    </html>
  );
}
