import "@/styles/globals.css";
import "@/styles/fonts.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "base",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
